name: putone
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Riverpod
  flutter_hooks:
  hooks_riverpod:

  # Entity
  freezed_annotation:
  json_annotation:
  equatable:

  # Image
  flutter_svg:

  # Permission
  permission_handler:

  # Other
  gap:
  blur: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Serializer
  json_serializable:

  # Code generator
  build_runner:
  freezed: ^2.3.5

  # Other
  flutter_launcher_icons:
  tiktoklikescroller: ^0.2.5
  audioplayers: ^5.1.0

flutter:
  assets:
    - assets/images/
    - assets/svgs/
    - assets/music/

  uses-material-design: true
