
name: Build iOS

on: push

jobs:
  run_build:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0
      - uses: kuhnroyal/flutter-fvm-config-action@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Cache Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
            
      - name: Set Up Ruby 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: Install Bundled Gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
        
      - name: Setup fvm
        run: |
          flutter pub global activate fvm
          fvm install

      - name: Setup Flutter
        run: make setup

      - name: Flutter iOS Build
        run: |
          fvm flutter build ios --no-codesign
